# Generated by Django 5.2.17 on 2026-09-22 21:58

import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de comisión',
                'verbose_name_plural': 'Configuración de comisión',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('pse', 'PSE'), ('billetera', 'Billetera digital')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=15)),
                ('referencia_pasarela', models.CharField(blank=True, max_length=100)),
                ('motivo_fallo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener solo números, entre 6 y 10 dígitos.', regex='^\\d{6,10}$')])),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('tecnico', 'Técnico'), ('administrador', 'Administrador')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pendiente_aprobacion', 'Pendiente de aprobación'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido')], default='activo', max_length=25)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('motivo_suspension', models.CharField(blank=True, max_length=300)),
                ('fecha_suspension', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=300)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_comision', models.DecimalField(decimal_places=0, max_digits=10)),
                ('monto_neto_tecnico', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='core.pago')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('cerrajeria', 'Cerrajería'), ('electrodomesticos', 'Electrodomésticos'), ('otro', 'Otro')], max_length=30)),
                ('ciudad', models.CharField(max_length=100)),
                ('documento_certificacion', models.FileField(upload_to='certificaciones/', validators=[core.validators.validar_certificacion])),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('precio_referencia', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('zona_cobertura', models.CharField(blank=True, max_length=255)),
                ('disponible', models.BooleanField(default=False)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_calificaciones', models.PositiveIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de técnico',
                'verbose_name_plural': 'Perfiles de técnico',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('cerrajeria', 'Cerrajería'), ('electrodomesticos', 'Electrodomésticos'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)])),
                ('direccion', models.CharField(max_length=255)),
                ('urgencia', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('notas_finales', models.CharField(blank=True, max_length=300)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('rechazada_por', models.ManyToManyField(blank=True, related_name='solicitudes_rechazadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, limit_choices_to={'rol': 'tecnico'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='core.solicitud'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud_creada', 'Solicitud creada'), ('solicitud_aceptada', 'Solicitud aceptada'), ('solicitud_finalizada', 'Solicitud finalizada'), ('tecnico_aprobado', 'Técnico aprobado'), ('tecnico_rechazado', 'Técnico rechazado'), ('info_solicitada', 'Información solicitada'), ('usuario_suspendido', 'Usuario suspendido'), ('pago_exitoso', 'Pago exitoso'), ('pago_fallido', 'Pago fallido')], max_length=25)),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.solicitud')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FotoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='solicitudes/', validators=[core.validators.validar_foto])),
                ('tipo', models.CharField(choices=[('evidencia', 'Evidencia del daño'), ('finalizacion', 'Evidencia de finalización')], default='evidencia', max_length=15)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.CharField(blank=True, max_length=300)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='core.solicitud')),
            ],
        ),
    ]
